In [1]:
#Numpy

In [2]:
%pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [3]:
import numpy as np

In [4]:
#Creating Array

In [5]:
sample_array=np.array([1,2,3,4])

In [6]:
sample_array

array([1, 2, 3, 4])

In [11]:
sample_array2=np.array([1,2,12])

In [12]:
sample_array2

array([ 1,  2, 12])

In [14]:
# 2D Array(a Matrix) with 2 rows and 2 columns

In [16]:
sample_array_2=np.array([[1,2],[3,4]])

In [19]:
sample_array_2

array([[1, 2],
       [3, 4]])

In [21]:
sample_array_3=np.array([[1,2,3],[4,5,6],[5,6,7]])

In [22]:
sample_array_3

array([[1, 2, 3],
       [4, 5, 6],
       [5, 6, 7]])

In [23]:
# 3D Tensor (2 matrices,each with 2 rows and 2 columns)

In [25]:
sample_tensor_3=np.array([[[1,2],[2,3]],[[3,4],[6,7]]])

In [26]:
sample_tensor_3

array([[[1, 2],
        [2, 3]],

       [[3, 4],
        [6, 7]]])

In [27]:
sample_tensor_4=np.array([[[11,12],[13,14]],[[15,16],[17,18]]])

In [28]:
sample_tensor_4

array([[[11, 12],
        [13, 14]],

       [[15, 16],
        [17, 18]]])

In [29]:
# Dimension

In [30]:
#Jar Array 0D->Scalar E.g 5
#Jar Array 1D->Vector E.g[1,2,3,4]
#Jar Array 2D->Matrix E.g [rows,colums]
#Jar Aray 3D->Tensor E.g [pages,rows,colums]

In [31]:
#Array Properties

In [32]:
sample_array_2=np.array([[1,2],[2,3]])

In [34]:
print(sample_array_2)

[[1 2]
 [2 3]]


In [35]:
#Check Shape of Array

In [36]:
sample_array_2.shape

(2, 2)

In [ ]:
#Checking Dimension

In [37]:

sample_array_2.ndim

2

In [38]:
#total elements

In [39]:
sample_array_2.size

4

In [43]:
# Data Type

In [44]:
sample_array_2.dtype

dtype('int64')

In [45]:
#Cheking Properties of 3rd Array

In [46]:
sample_array=np.array([[[1,2],[2,3]],[[4,5],[5,6]]])

In [47]:
sample_array

array([[[1, 2],
        [2, 3]],

       [[4, 5],
        [5, 6]]])

In [48]:
#cheking shape

In [49]:
sample_array.shape

(2, 2, 2)

In [50]:
#Checking Deminsion

In [51]:
sample_array.ndim

3

In [52]:
#Total number of element

In [53]:
sample_array.size

8

In [54]:
#Datatype

In [55]:
sample_array.dtype

dtype('int64')

In [56]:
#Special Array

In [57]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [59]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [60]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [61]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [62]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [63]:
np.ones((7,7))

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [64]:
np.arange(0,10,2) 

array([0, 2, 4, 6, 8])

In [65]:
np.arange(10,0,-2)

array([10,  8,  6,  4,  2])

In [66]:
np.arange(0,100,2) 

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [71]:
np.arange(0,10,5)

array([0, 5])

In [73]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [77]:
np.linspace(5,8,1)

array([5.])

In [78]:
#indexing and slicing

In [79]:
sample_array=np.array([10,20,30,40])

In [80]:
sample_array

array([10, 20, 30, 40])

In [81]:
sample_array[0]

np.int64(10)

In [82]:
sample_array[1]

np.int64(20)

In [83]:
sample_array[3]

np.int64(40)

In [85]:
sample_array[2]

np.int64(30)

In [86]:
sample_array[-1]

np.int64(40)

In [87]:
sample_array[-2]

np.int64(30)

In [88]:
sample_array[-3]

np.int64(20)

In [89]:
#Slicing

In [92]:
sample_array[0:4]

array([10, 20, 30, 40])

In [93]:
sample_array[:]

array([10, 20, 30, 40])

In [97]:
sample_array[::]

array([10, 20, 30, 40])

In [98]:
a=np.array([1,2,3])

In [99]:
b=np.array([4,5,6])

In [100]:
a

array([1, 2, 3])

In [101]:
b

array([4, 5, 6])

In [102]:
a + b

array([5, 7, 9])

In [103]:
a - b

array([-3, -3, -3])

In [104]:
a * b

array([ 4, 10, 18])

In [105]:
a / b

array([0.25, 0.4 , 0.5 ])

In [113]:
x=np.array([56,13,45])

In [114]:
y=np.array([56,46,23])

In [115]:
x + y

array([112,  59,  68])

In [116]:
x - y

array([  0, -33,  22])

In [117]:
x*y

array([3136,  598, 1035])

In [118]:
x/y

array([1.        , 0.2826087 , 1.95652174])

In [119]:
x//y

array([1, 0, 1])

In [120]:
# Mathematical Functions

In [4]:
sample_array=np.array([1,4,9])

In [5]:
sample_array

array([1, 4, 9])

In [6]:
np.sqrt(sample_array)

array([1., 2., 3.])

In [7]:
sample_array=np.array([3456,456,785])

In [8]:
np.sqrt(sample_array)

array([58.78775383, 21.3541565 , 28.01785145])

In [9]:
import numpy as np

In [11]:
sample_array=([1,2,3,4])

In [12]:
np.exp(sample_array)

array([ 2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [13]:
np.log(sample_array)

array([0.        , 0.69314718, 1.09861229, 1.38629436])

In [14]:
sample_array=([111,3456,674])

In [15]:
np.log(sample_array)

array([4.7095302 , 8.14786713, 6.51323011])

In [16]:
# Statistiacl Function

In [19]:
sample=np.array([1,2,3,4,5])

In [20]:
sample

array([1, 2, 3, 4, 5])

In [21]:
np.mean(sample)

np.float64(3.0)

In [22]:
np.median(sample)

np.float64(3.0)

In [25]:
np.std(sample)

np.float64(1.4142135623730951)

In [26]:
np.min(sample)

np.int64(1)

In [27]:
np.max(sample)

np.int64(5)

In [28]:
# ReShaping Array

In [32]:
sample_array=np.arange(0,6)

In [33]:
sample_array

array([0, 1, 2, 3, 4, 5])

In [38]:
reshape=sample_array.reshape((2,3))

In [39]:
reshape

array([[0, 1, 2],
       [3, 4, 5]])

In [40]:
sample_array

array([0, 1, 2, 3, 4, 5])

In [41]:
# Array Flatting -> Converting 3D,2D array into 1D

In [42]:
sample_array=np.array([[1,2],[3,4]])

In [43]:
sample_array

array([[1, 2],
       [3, 4]])

In [45]:
sample_array.flatten()

array([1, 2, 3, 4])

In [46]:
sample_array=np.array([[[1,2],[2,3]],[[4,5],[5,6]]])

In [47]:
sample_array.flatten()

array([1, 2, 2, 3, 4, 5, 5, 6])

In [49]:
# Joinig Arrays

In [50]:
x=np.array([1,2,3,4,5])


In [53]:
y=np.array([1,2,8,9,10])

In [59]:
np.concatenate((x,y))

array([ 1,  2,  3,  4,  5,  1,  2,  8,  9, 10])

In [61]:
np.concat((x,y))

array([ 1,  2,  3,  4,  5,  1,  2,  8,  9, 10])

In [64]:
# Spliting Arrays

In [65]:
sample=np.array([1,2,3,4])

In [66]:
dir(np)

['False_',
 'ScalarType',
 'True_',
 '_CopyMode',
 '_NoValue',
 '__NUMPY_SETUP__',
 '__all__',
 '__array_api_version__',
 '__array_namespace_info__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__dir__',
 '__doc__',
 '__expired_attributes__',
 '__file__',
 '__former_attrs__',
 '__future_scalars__',
 '__getattr__',
 '__loader__',
 '__name__',
 '__numpy_submodules__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_array_api_info',
 '_core',
 '_distributor_init',
 '_expired_attrs_2_0',
 '_globals',
 '_int_extended_msg',
 '_mat',
 '_msg',
 '_pyinstaller_hooks_dir',
 '_pytesttester',
 '_specific_msg',
 '_type_info',
 '_typing',
 '_utils',
 'abs',
 'absolute',
 'acos',
 'acosh',
 'add',
 'all',
 'allclose',
 'amax',
 'amin',
 'angle',
 'any',
 'append',
 'apply_along_axis',
 'apply_over_axes',
 'arange',
 'arccos',
 'arccosh',
 'arcsin',
 'arcsinh',
 'arctan',
 'arctan2',
 'arctanh',
 'argmax',
 'argmin',
 'argpartition',
 'argsort',
 'argwhere',
 'around',
 'array',
 'arr

In [67]:
sample

array([1, 2, 3, 4])

In [68]:
np.array_split(sample,2)

[array([1, 2]), array([3, 4])]

In [72]:
np.array_split(sample,6)

[array([1]),
 array([2]),
 array([3]),
 array([4]),
 array([], dtype=int64),
 array([], dtype=int64)]

In [74]:
# Random Module

In [79]:
np.random.rand(3)  # Give Floating random value

array([0.47521453, 0.99553446, 0.2052238 ])

In [82]:
np.random.randint(1,10,5)

array([6, 5, 5, 1, 6], dtype=int32)

In [84]:
# Axis Concept->

In [85]:
array=np.array([[1,2,3],[3,4,5]])

In [86]:
array

array([[1, 2, 3],
       [3, 4, 5]])

In [87]:
# Rows Axix->1 for rows sum
#Colums Axix->0 for columns sum

In [88]:
np.sum(array,axis=0)

array([4, 6, 8])

In [90]:
np.sum(array,axis=1)

array([ 6, 12])

In [91]:
# NaN and Missing Value

In [95]:
sample=np.array([1,np.nan,3])

In [96]:
sample

array([ 1., nan,  3.])

In [97]:
np.isnan(sample)

array([False,  True, False])

In [98]:
# Create 2 Numpy Array and Perform element wise addition,subtraction,multiplication and moduls operation

In [99]:
num1=np.array([10,20,30,40,50])  

In [100]:
num2=np.array([60,70,80,90,100])

In [101]:
add_array=num1+num2

In [103]:
add_array

array([ 70,  90, 110, 130, 150])

In [104]:
sub_array=num1-num2

In [105]:
sub_array

array([-50, -50, -50, -50, -50])

In [106]:
mul_array=num1*num2

In [107]:
mul_array

array([ 600, 1400, 2400, 3600, 5000])

In [108]:
mod_array=num1%num2

In [109]:
mod_array

array([10, 20, 30, 40, 50])