# Practice

## Numpy

In [1]:
import numpy as np

In [2]:
sample=np.array([1,2,3,4])

In [3]:
sample

array([1, 2, 3, 4])

In [4]:
#Creating 0D Array -->Scalar

In [5]:
sample1=np.array(7)

In [6]:
sample1

array(7)

In [7]:
#Creating 1D Array -->Vector

In [8]:
sample1=np.array([1,2,3,4])

In [9]:
sample1

array([1, 2, 3, 4])

In [10]:
#Creating 2D Array

In [11]:
sample1=np.array([[1,2],[3,4]])

In [12]:
sample1

array([[1, 2],
       [3, 4]])

In [13]:
#Creating 3D Array

In [14]:
sample1=np.array([[[1,2],[3,4]],[[5,6],[8,9]]])

In [15]:
sample1

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [8, 9]]])

In [17]:
#checking of Array of 3D

In [18]:
sample1.shape

(2, 2, 2)

In [19]:
sample1.size

8

In [20]:
sample1.ndim

3

In [21]:
sample1.dtype

dtype('int64')

In [22]:
#Special Array

In [28]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [29]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [30]:
np.linspace(1,2,5)

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

In [31]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [32]:
# Accessing or Slicing

In [33]:
sample1=np.array([1,2,3,4])

In [35]:
sample1[0]

np.int64(1)

In [36]:
sample1[1]

np.int64(2)

In [37]:
sample1[1:3]

array([2, 3])

In [38]:
sample1[::]

array([1, 2, 3, 4])

In [39]:
sample[::-1]

array([4, 3, 2, 1])

In [40]:
# Math Function of array

In [42]:
np.sqrt(sample1)

array([1.        , 1.41421356, 1.73205081, 2.        ])

In [43]:
np.log(sample1)

array([0.        , 0.69314718, 1.09861229, 1.38629436])

In [44]:
np.exp(sample1)

array([ 2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [45]:
# Perform operation Maths on array

In [47]:
a=np.array([1,2,3,4])

In [48]:
b=np.array([5,6,7,8])

In [49]:
a+b

array([ 6,  8, 10, 12])

In [50]:
a-b

array([-4, -4, -4, -4])

In [51]:
a*b

array([ 5, 12, 21, 32])

In [52]:
a//b

array([0, 0, 0, 0])

In [53]:
a%b

array([1, 2, 3, 4])

In [54]:
# Random Module

In [55]:
np.random.rand(3)

array([0.70807101, 0.25829524, 0.02393745])

In [56]:
np.random.randint(1,10,3)

array([4, 7, 8], dtype=int32)

# Pandas 

In [57]:
import pandas as  pd

In [58]:
series=pd.Series([1,2,3,4,5])

In [59]:
series

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [61]:
series=pd.Series([1,2,3,5],index=[1,2,3,4])

In [62]:
series

1    1
2    2
3    3
4    5
dtype: int64

In [63]:
series=pd.Series([1,2,3,4,5],index=['a','b','c','d','e'])

In [64]:
series

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [65]:
# Series Properties

In [66]:
series.index

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

In [67]:
series.values

array([1, 2, 3, 4, 5])

In [69]:
series.values

array([1, 2, 3, 4, 5])

In [70]:
s=pd.Series([10,20,None,40])

In [71]:
s

0    10.0
1    20.0
2     NaN
3    40.0
dtype: float64

In [75]:
s.dropna()

0    10.0
1    20.0
3    40.0
dtype: float64

In [76]:
s.isnull()

0    False
1    False
2     True
3    False
dtype: bool

In [77]:
s.fillna(10)

0    10.0
1    20.0
2    10.0
3    40.0
dtype: float64

In [79]:
# Data Maniplate

In [81]:
s*4

0     40.0
1     80.0
2      NaN
3    160.0
dtype: float64

In [82]:
# Series Properties

In [83]:
s=pd.Series([1,2,3,4,5])

In [84]:
s.shape

(5,)

In [85]:
s.ndim

1

In [86]:
s.size

5

In [87]:
# Accessing Element Via Index and Slicing

In [88]:
s=pd.Series([1,2,3,4,5,6,7,8,8])

In [89]:
s[0]

np.int64(1)

In [90]:
s[1:5]

1    2
2    3
3    4
4    5
dtype: int64

In [95]:
s.index

RangeIndex(start=0, stop=9, step=1)